### ISSUE TITLE
Drop party ideas

### ISSUE THREAD

**Issue by renzotom** [Ben12345rocks/AdvancedMobControl#1]
- [ ] When drop party starts, all players earn reward - special drop, beacuse they reach ex. 10 killed blazes
- [ ] When drop party starts, it will remain untill set time and ->
- [ ] Mobs will have more health
- [ ] Mobs will have less health
- [ ] Mobs will have smaller damage
- [ ] Mobs will have bigger damage
- [ ] Mobs will spawn more
- [ ] Mobs will spawn less
- [ ] Players earn more rewards, we can set what (when drop party starts)
- [ ] Execute command, when drop party start
- [ ] Execute command, when vote party ends
- [ ] Command to start party
- [ ] Command to end party
- [ ] Schedule for drop party, in real time (ex. party starts in 1pm and ends in 10pm)
- [ ] Shcedule for drop party in Minecraft time (Minecraft time- ex. party starts in 1pm and ends in 10pm)
- [ ] When certain number of mobs is killed, drop party starts
- [ ] Per-mob drop party
- [ ] Per-world drop party
- [ ] Per-server (bungee) drop party
- [ ] Per-permission support (if player is VIP, he earn better reward)
- [ ] Per-group support (when player is VIP, he need less or more mobs killed to start drop party)
- [ ] It is eula friendly, beacuse player can buy this and all server have drop party
- [ ] Cumulative drop party per hour (when are two, three, four drop parties in hour, they earn bigger or smaller reward)
- [ ] Cumulative drop party per day  (when are two, three, four... drop parties in day, they earn bigger or smaller reward)
- [ ] Cumulative drop party per week  (when are two, three, four... drop parties in week, they earn bigger or smaller reward)
- [ ] Cumulative drop party per month  (when are two, three, four... drop parties in month, they earn bigger or smaller reward)
- [ ] Per-locations support
- [ ] Drop party in special locations (support residence, regions...)
- [ ] Temportally drop party in special locations, ex. when drop party starts, it starts only in spawn (residence/region) and drop party will be there 
- [ ] Temportally rewards in special locations, ex. when drop party starts, players will earn special rewards only in spawn (residence/region) and drop party will be there 
- [ ] Temportally health in special locations, ex. when drop party starts, mobs will have less or more health only in spawn (residence/region) and drop party will be there 
- [ ] Temportally damage in special locations, ex. when drop party starts, mobs will have less or more damage only in spawn (residence/region) and drop party will be there 
- [ ] Temportally rewards in special locations, ex. when drop party starts, players will earn rewards only in spawn (it disable normal vote in other locations) (residence/region) and drop party will be there 
- [ ] Temportally rewards in special locations, ex. when drop party starts, mobs will spawn only on spawn (it disable normal vote in other locations) (residence/region) and drop party will be there

**Comment by BenCodez** [comment]
Gonna close this, as most of these features are really unneeded.

**Comment by renzotom** [comment]
Ok, so maybe later?
