### ISSUE TITLE
Rewards for killing mob

### ISSUE THREAD

**Issue by renzotom** [Ben12345rocks/AdvancedMobControl#2]
- [ ] When player kill mob, he earn food
- [ ] When player kill mob, he earn health
- [ ] When player kill mob, he earn ex. one extra hearth
- [ ] When player kill mob, it do firework
- [ ] When player kill mob, he earn permission
- [ ] When player kill mob, it execute command
- [ ] When player kill mob, he potion effect
- [ ] When player kill mob, it show player above hotbar message
- [ ] When player kill mob, it show player in boss bar message
- [ ] When player kill mob, it show player in chat message
- [ ] When player kill mob, it show player hologram with message
- [ ] When player kill mob, it show player title and subtitle with message
- [ ] When player kill mob first time, he earn special reward
- [ ]  When player kill mob first time, he earn ex. 2 money, when in second time, he earn 4 money, when in third time, he earn 10 money and next....
- [ ] When player kill mob ten time or twenty time... he earn special reward
- [ ] Drop party, more info in https://github.com/Ben12345rocks/AdvancedMobControl/issues/1
- [ ] Min hour kill mobs, when player doesn´t reach this, it execute command
- [ ] Max hour kill mobs, when player reach this, it execute command

**Comment by BenCodez** [comment]
@renzotom 
I'll probably setup reward files to do this. Similar to VotingPlugin

**Comment by renzotom** [comment]
I also write here ideas from VotingPlugin and some others :D

**Comment by BenCodez** [comment]
@renzotom 
Noticed, I'll probably port over the stuff from votingplugin

**Comment by renzotom** [comment]
There are also rewards, what aren´t available now, no?

**Comment by BenCodez** [comment]
@renzotom All these things can be done already, or will be able to when I add more stuff to reward files

**Comment by renzotom** [comment]
Ok
