### ISSUE TITLE
Looting XP

### ISSUE THREAD

**Issue by renzotom** [Ben12345rocks/AdvancedMobControl#20]
Can you add, if player has looting on sword and kill monster, we can set % how many XP will drop?

**Comment by BenCodez** [comment]
I'll take a look at it.

**Comment by BenCodez** [comment]
Added a way to set custom mob drops based on looting level, as for looting xp, I'll take a look at that later. Gonna close this and write that down on my version plans.

**Comment by renzotom** [comment]
Thank you.

**Comment by renzotom** [comment]
Wait, so it is done or no? I am confused :D .

**Comment by BenCodez** [comment]
No, but I added custom mob drops based on looting level.

**Comment by renzotom** [comment]
And you add also XP soon?

**Comment by BenCodez** [comment]
Soon.
