### ISSUE TITLE
Config is empty?

### ISSUE THREAD

**Issue by renzotom** [Ben12345rocks/AdvancedMobControl#21]
Hello Ben12345rocks I am back.

`[17:11:33] [Server thread/WARN]: [AdvancedMobControl] Could not save Config.yml to plugins/AdvancedMobControl/Config.yml because Config.yml already exists.`
I was uploaded plugin to my plugins folder and it created folder AdvancedMobControl. Now, there is empty config, which has 0 kb.

**Comment by BenCodez** [comment]
Delete the file and restart. If that doesn't work then just copy it from github.

**Comment by renzotom** [comment]
I copied it

**Comment by renzotom** [comment]
And why there wasn´t config file?

**Comment by BenCodez** [comment]
You probably uploaded one while it tried to generate one.
