### ISSUE TITLE
Voting???

### ISSUE THREAD

**Issue by renzotom** [Ben12345rocks/AdvancedMobControl#22]
`    
# Title to send to **voter**
Title:
  Enabled: false
  Title: '&cThanks for voting!'
  SubTitle: '&aYou voted on a website!'
  FadeIn: 10
  ShowTime: 50
  FadeOut: 10`

What voting in that plugin?

**Comment by BenCodez** [comment]
Oh whoops. I'll fix that when I get around to it.

**Comment by renzotom** [comment]
This is in reward file, why?

**Comment by BenCodez** [comment]
I just never noticed that.

**Comment by renzotom** [comment]
??? I don´ t understand you now

**Comment by BenCodez** [comment]
It will be fixed in a coming update (Whenever I get time)
