### ISSUE TITLE
1.7 Version Plans

### ISSUE THREAD

**Issue by BenCodez** [Ben12345rocks/AdvancedMobControl#3]
- [ ] Per world control
- [ ] Spawner support?

**Comment by renzotom** [comment]
Yey, I looking forward to new version.

**Comment by renzotom** [comment]
It is 1.3, no? Beacuse you already released 1.2.

**Comment by Ben12345rocks** [comment]
@renzotom 
Fixed :)

**Comment by renzotom** [comment]
It will be in September?

**Comment by Ben12345rocks** [comment]
@renzotom No idea

**Comment by renzotom** [comment]
Something new here?

**Comment by Ben12345rocks** [comment]
?
