### ISSUE TITLE
Main page on spigot and github

### ISSUE THREAD

**Issue by renzotom** [Ben12345rocks/AdvancedMobControl#4]
Hello, you can add this on main page on spigot:
- [ ] Plugin icon
- [ ]  More images with sections
- [ ]  More videos (tutorials) I try make Czech and Slovakia tutorial for you
- [ ] Maybe make instead of bold text images, ex. image FEATURES ? (special text)
- [ ] Maybe when you gain more reviews, put some on your main page
- [ ] Also create WIKI

**Comment by BenCodez** [comment]
Gonna close this, as some I've done or do yet.

**Comment by renzotom** [comment]
Ok
