### ISSUE TITLE
Total

### ISSUE THREAD

**Issue by renzotom** [Ben12345rocks/AdvancedMobControl#5]
- [ ] Make command for best killer
- [ ] Make command for best killer per-servers, per-world, per-mobs, per-groups
- [ ] LeaderBoard in chat
- [ ] LeaderBoard in scoreboard
- [ ] LeaderBoard in hologram
- [ ] LeaderBoard on web
- [ ] LeaderBoard on signs
- [ ] Hourly awards to best killers
- [ ] Daily awards to best killers
- [ ] Weekly awards to best killers
- [ ] Monthly awards to best killers

**Comment by BenCodez** [comment]
Gonna close this as some features are really unneeded, but write this down on as a possible feature

**Comment by renzotom** [comment]
I think, that can be good :( .
