### ISSUE TITLE
Next ideas

### ISSUE THREAD

**Issue by renzotom** [Ben12345rocks/AdvancedMobControl#6]
- [ ] Tab complete commands
- [ ] More placeholders and add also to PlaceHolderAPI
- [ ] More GUI (I suggest it in main plugin and in VotingPlugin)
- [ ] ScoreBoards
- [ ] Points 
- [ ] Addons (I don´t know what now)
- [ ] Suport for MythicMobs (it can be in drop party or something else)
- [ ] MYSQL and SQL support
- [ ] Support java 7
- [ ] Language folder with files
- [ ] Log file
- [ ] Report folder
- [ ] Animated messages

**Comment by BenCodez** [comment]
@renzotom 
Already supports uuids. I'm not gonna bother with a converter, as this is easy to setup atm.

**Comment by renzotom** [comment]
I mean converter of statistic for players (beacuse they can lose their scores). And sorry, you can write about UUIDS on main page, as in VotingPlugin.

**Comment by BenCodez** [comment]
@renzotom 
Atm the plugin doesn't track statistics, so I don't need that yet.
Added the UUID support to the main page.

**Comment by renzotom** [comment]
Oh sorry. But, when it will be harder (or there will be more features), you can add it, no?  + I edit it with next things.

**Comment by BenCodez** [comment]
@renzotom Maybe.

**Comment by BenCodez** [comment]
Don't really need some of these, will get around to some though.
Closing for now.
