### ISSUE TITLE
Bungee

### ISSUE THREAD

**Issue by renzotom** [Ben12345rocks/AdvancedMobControl#7]
- [ ] Add support for Bungee
- [ ] Add support for total in Bungee - https://github.com/Ben12345rocks/AdvancedMobControl/issues/5
- [ ]  Add support for Drop party in Bungee - https://github.com/Ben12345rocks/AdvancedMobControl/issues/1

**Comment by BenCodez** [comment]
@renzotom 
Probably won't do this soon, but will look into it.

**Comment by renzotom** [comment]
I don´t need it, I don´t use bungee now, but maybe soon... You can do it, when you have time, nobody contact you about bungee support.

**Comment by BenCodez** [comment]
Closing this for now, not really needed
